server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启动态路由
      routes:
        - id: payment_route1  #请求 http://localhost:8100/data-service1/test会转发到data-producer服务
          #uri: http://localhost:8001  #在服务注册中心找服务名为 data-producer的服务
          uri: lb://cloud-payment-service #lb标识负载均衡
          predicates:
            - Path=/payment/get/**  #设置路由断言,代理servicerId为data-service1的/ data-service1 /路径
        - id: payment_route2  # 请求 http://localhost:8100/data-service2/test转发到 http://localhost:8080/test
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            #- After=2021-02-18T22:58:03.646+08:00[Asia/Shanghai] #在该时区后发生
            #- Cookie=username,haugv
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      fetch-registry: true
      register-with-eureka: true
